In [1]:
import os 
import pandas as pd

In [2]:
raw_dir = "../data/raw"
processed_dir = "../data/processed"

In [3]:
consumption_list = []
years = range(2018,2026)

In [4]:
for year in years:
    consumption_path = os.path.join(raw_dir, f"consumption_data_{year}.csv")
    if os.path.exists(consumption_path):
        df = pd.read_csv(consumption_path)
        consumption_list.append(df)
    else:
        print(f"File not found: {consumption_path}. Check the file path.")

In [5]:
consumption_df = pd.concat(consumption_list, ignore_index=True)

In [6]:
consumption_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70128 entries, 0 to 70127
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         70128 non-null  object
 1   time         70128 non-null  object
 2   consumption  70128 non-null  float64
dtypes: float64(1), object(2)
memory usage: 1.6+ MB

In [7]:
consumption_df.isna().sum()

date           0
time           0
consumption    0
dtype: int64

In [8]:
consumption_df.duplicated().sum()

np.int64(0)

In [9]:
consumption_df.head()

                        date   time  consumption
0  2018-01-01T00:00:00+03:00  00:00     27412.81
1  2018-01-01T01:00:00+03:00  01:00     26324.39
2  2018-01-01T02:00:00+03:00  02:00     24635.32
3  2018-01-01T03:00:00+03:00  03:00     23872.12
4  2018-01-01T04:00:00+03:00  04:00     23194.89

In [10]:
consumption_df.tail()

                            date   time  consumption
70123  2025-12-31T19:00:00+03:00  19:00     42817.12
70124  2025-12-31T20:00:00+03:00  20:00     40604.13
70125  2025-12-31T21:00:00+03:00  21:00     38715.64
70126  2025-12-31T22:00:00+03:00  22:00     37317.11
70127  2025-12-31T23:00:00+03:00  23:00     35214.44

In [11]:
generation_list = []

for year in years:
    generation_path = os.path.join(raw_dir, f"generation_data_{year}.csv")
    if os.path.exists(generation_path):
        df = pd.read_csv(generation_path)
        generation_list.append(df)
    else:
        print(f"File not found: {generation_path}. Check the file path.")

In [12]:
generation_df = pd.concat(generation_list, ignore_index=True)

In [13]:
generation_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70128 entries, 0 to 70127
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            70128 non-null  object
 1   hour            70128 non-null  object
 2   total           70128 non-null  float64
 3   naturalGas      70128 non-null  float64
 4   dammedHydro     70128 non-null  float64
 5   lignite         70128 non-null  float64
 6   river           70128 non-null  float64
 7   importCoal      70128 non-null  float64
 8   wind            70128 non-null  float64
 9   sun             70128 non-null  float64
 10  fueloil         70128 non-null  float64
 11  geothermal      70128 non-null  float64
 12  asphaltiteCoal  70128 non-null  float64
 13  blackCoal       70128 non-null  float64
 14  biomass         70128 non-null  float64
 15  naphta          70128 non-null  int64
 16  lng             70128 non-null  float64
 17  importExport    70128 non-null  float64
 18  wasteheat       70128 non-null  float64
dtypes: float64(16), int64(1), object(2)
memory usage: 10.2+ MB

In [14]:
generation_df.duplicated().sum()

np.int64(0)

In [15]:
generation_df.isna().sum()

date              0
hour              0
total             0
naturalGas        0
dammedHydro       0
lignite           0
river             0
importCoal        0
wind              0
sun               0
fueloil           0
geothermal        0
asphaltiteCoal    0
blackCoal         0
biomass           0
naphta            0
lng               0
importExport      0
wasteheat         0
dtype: int64

In [16]:
generation_df = generation_df.rename(columns={"total":"total_generation"})

In [17]:
generation_df.head()

,date,hour,total_generation,naturalGas,dammedHydro,lignite,river,importCoal,wind,sun,fueloil,geothermal,asphaltiteCoal,blackCoal,biomass,naphta,lng,importExport,wasteheat
0,2018-01-01T00:00:00+03:00,00:00,27412.81,6926.78,4820.40,5226.32,1900.32,5314.05,1179.51,0.0,176.60,801.09,278.20,189.5,210.96,0,0.0,297.0,92.08
1,2018-01-01T01:00:00+03:00,01:00,26324.39,6603.44,3644.32,5277.19,1877.83,5715.61,1148.46,0.0,174.20,803.21,284.82,205.5,211.67,0,0.0,287.0,91.14
2,2018-01-01T02:00:00+03:00,02:00,24635.32,6040.77,2711.00,5325.47,1708.49,5701.37,1216.38,0.0,177.91,804.28,278.20,201.5,209.89,0,0.0,169.0,91.06
3,2018-01-01T03:00:00+03:00,03:00,23872.12,5938.46,2524.37,5265.91,1662.59,5205.43,1298.11,0.0,171.50,805.61,271.57,211.5,211.24,0,0.0,214.0,91.83
4,2018-01-01T04:00:00+03:00,04:00,23194.89,5665.41,2462.71,5282.88,1697.96,4804.19,1220.91,0.0,165.00,806.01,273.78,307.5,214.31,0,0.0,203.0,91.23

In [18]:
generation_df.tail()

,date,hour,total_generation,naturalGas,dammedHydro,lignite,river,importCoal,wind,sun,fueloil,geothermal,asphaltiteCoal,blackCoal,biomass,naphta,lng,importExport,wasteheat
70123,2025-12-31T19:00:00+03:00,19:00,42810.19,13948.08,5825.86,4650.09,1410.53,10119.60,4319.39,2.11,74.11,1389.36,214.16,599.77,970.98,0,0.0,-791.84,77.99
70124,2025-12-31T20:00:00+03:00,20:00,40590.15,12903.12,4907.93,4753.23,1252.12,10123.76,4056.07,1.91,75.25,1393.21,218.58,602.17,975.73,0,0.0,-748.98,76.05
70125,2025-12-31T21:00:00+03:00,21:00,38705.89,12175.30,4244.06,4721.91,1268.20,10054.23,3658.79,1.88,73.98,1391.52,220.79,596.61,972.74,0,0.0,-751.40,77.28
70126,2025-12-31T22:00:00+03:00,22:00,37308.50,11317.22,4488.62,4726.76,1096.94,9524.73,3441.91,1.85,73.78,1396.17,216.37,594.83,967.53,0,0.0,-613.67,75.46
70127,2025-12-31T23:00:00+03:00,23:00,35216.01,9767.29,4257.36,4705.42,881.47,9896.33,2885.45,1.84,75.47,1397.72,220.79,608.48,948.17,0,0.0,-507.68,77.90

In [19]:
consumption_df["date"] = pd.to_datetime(consumption_df["date"], format="%Y-%m-%dT%H:%M:%S+03:00")

In [20]:
print(consumption_df['date'].dtype)

datetime64[ns]

In [21]:
consumption_df = consumption_df.sort_values("date").reset_index(drop=True)

In [22]:
print(consumption_df["date"].min())
print(consumption_df["date"].max())

2018-01-01 00:00:00
2025-12-31 23:00:00

In [23]:
generation_df["date"] = pd.to_datetime(generation_df["date"], format="%Y-%m-%dT%H:%M:%S+03:00")

In [24]:
print(generation_df['date'].dtype)

datetime64[ns]

In [25]:
generation_df = generation_df.sort_values("date").reset_index(drop=True)

In [26]:
print(generation_df["date"].min())
print(generation_df["date"].max())

2018-01-01 00:00:00
2025-12-31 23:00:00

In [27]:
consumption_df.to_csv(os.path.join(processed_dir, "consumption.csv"), index=False)
generation_df.to_csv(os.path.join(processed_dir, "generation.csv"), index=False)

In [28]:
consumption_df.to_parquet(os.path.join(processed_dir, "consumption.parquet"))
generation_df.to_parquet(os.path.join(processed_dir, "generation.parquet"))